### ISSUE TITLE
upgrade parser versions

### ISSUE THREAD

**Issue by tjx666** [Arichy/vscode-ast-explorer#2]
This extension:

<img width="1070" alt="image" src="https://user-images.githubusercontent.com/41773861/188296390-0c7e2bdc-200e-4532-880c-cd3d37c1a8ea.png">

Official:

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/41773861/188296399-84ebe594-4390-499d-91a7-10073190889a.png">

**Comment by arichyx** [comment]
Upgraded in `1.2.0`.
