### ISSUE TITLE
[Feature Request] Simplify the UI interface

### ISSUE THREAD

**Issue by tjx666** [Arichy/vscode-ast-explorer#4]
The elements in red box is useless:

<img width="1075" alt="image" src="https://user-images.githubusercontent.com/41773861/188296484-db432bf1-bfdc-47ef-8894-ba0844058d6e.png">

**Comment by arichyx** [comment]
The first is removed, but the second button is not useless.It's for changing language manually.
I didn't see the box in the bottom, maybe remove it next time😁
