### ISSUE TITLE
More languages

### ISSUE THREAD

**Issue by Zireael07** [Arichy/vscode-ast-explorer#5]
The official AST explorer supports way more languages, eg. Lua or Go

**Comment by arichyx** [comment]
@Zireael07 Hi, when I developed the extension at 2021, I didn't have much experience about some tech stack like git submodules, lazy loading, so it was a very rough version.

Now I'm developing a new version, hopefully it would support more languages like Go and get synced with official AST explorer, but there are lots of challenges. For example, vscode extension has no server, so it does not support dynamic import, while all wasm parser (Go, Rust) relies on it currently. Bundling all files into one JS file would work, but the bundle size would be TOO large, resulting in a long loading time.

I'm trying striking a balance between bundle size and loading time, with more languages supported (may not support all languages).

**Comment by arichyx** [comment]
The latest v2.0.1 supported more languages.

**Comment by Zireael07** [comment]
Wow, that's super fast turnaround, based on your comment about challenges I was expecting to have to wait months or so ;)
